name: Main
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
          flutter-version: '3.7.7'
          channel: 'stable'
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
     - uses: actions/download-artifact@v3
       with:
        name: mock_client.app
        path: build/macos/Build/Products/Release/
