name: Main

on:
   workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
          flutter-version: '3.7.7'
          channel: 'stable'
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
     - name: Download a Build Artifact
     - uses: actions/download-artifact@v2.1.1
       with:
        # Artifact name
        name: client.app
        # Destination path
        path: build/macos/Build/Products/Release/mock_client.app
